export const ACTIONS_FORM = {
    SET_FORM_PRIMARY_ROOT: "SET_FORM_PRIMARY_ROOT",
    SET_FORM_LATERAL_ROOTS: "SET_FORM_LATERAL_ROOTS",
    SET_FORM_ADDITIONAL_INFO: "SET_FORM_ADDITIONAL_INFO",
    EMPTY_FORM: "EMPTY_FORM"
};
